apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring.fullName" . }}
  labels:
    {{- include "spring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spring.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spring.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: {{ .Chart.Name }}
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /system/health/liveness
            port: {{ .Chart.Name }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /system/health/readiness
            port: {{ .Chart.Name }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: secret-volume
          mountPath: /run/secrets/{{ include "spring.fullName" . }}
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ include "spring.fullName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
