apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring.fullName" . }}
  labels:
    {{- include "spring.labels" . | indent 4 }}
type: Opaque
data:
  mongodb.password: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  mongodb.username: {{ .Values.mongodb.auth.rootUser | b64enc }}
